---
- name: Dummy Spring Boot CI/CD Pipeline - All Success
  hosts: localhost
  gather_facts: no
  become: no

  vars:
    app_name: springboot-app
    jar_file: target/app.jar
    should_run_tests: true # <-- Simulate tests as executed

  tasks:
    - name: Stage 1 - Clean Workspace
      debug:
        msg: "Cleaning workspace..."

    - name: Stage 2 - Run Unit Tests
      debug:
        msg: "Running JUnit test cases... All passed."

    - name: Stage 3 - Maven Clean Install
      debug:
        msg: "Starting Maven build process..."

    - name: Maven Build Complete
      debug:
        msg: "Maven build completed successfully."

    - name: Stage 4 - Deploy to AWS
      debug:
        msg: "Deployed to AWS EC2 successfully."

    - name: Stage 5 - Deployment Complete
      debug:
        msg: "🎉 Deployment pipeline completed successfully!"
