---
  - name: Dummy Spring Boot CI/CD Pipeline with Mixed Outcomes
    hosts: localhost
    gather_facts: no
    become: no
  
    vars:
      app_name: springboot-app
      jar_file: target/app.jar
      should_run_tests: false  # <-- Change this to true to run tests
  
    tasks:
      - name: Stage 1 - Clean Workspace (Success)
        debug:
          msg: "Cleaning workspace..."
  
      - name: Stage 2 - Run Unit Tests (Simulated Skipped)
        debug:
          msg: "Running JUnit tests..."
        when: should_run_tests  # <-- will be skipped because it's false
  
      - name: Stage 3 - Maven Clean Install (Fail Simulated)
        fail:
          msg: "Maven build failed due to missing dependencies."
  
      - name: Stage 4 - Deploy to AWS (Skipped due to previous fail)
        debug:
          msg: "Deploying to AWS..."
        when: false
  
      - name: Stage 5 - Deployment Complete (Skipped)
        debug:
          msg: "🎉 Deployment simulation finished!"
        when: false