---
  - name: Dummy Spring Boot CI/CD Pipeline with Simulated Failure
    hosts: localhost
    gather_facts: no
    become: no
  
    vars:
      app_name: springboot-app
      jar_file: target/app.jar
  
    tasks:
      - name: Stage 1 - Clean Workspace
        debug:
          msg: "Cleaning workspace..."
  
      - name: Stage 2 - Maven Clean Install (Simulated Failure)
        block:
          - name: Running 'mvn clean install' (fail simulation)
            fail:
              msg: "Maven build failed due to missing dependencies."
        when: true  # simulate failure by always triggering this block
  
      - name: Stage 3 - Run Unit Tests
        debug:
          msg: "Running JUnit test cases..."
        when: false  # Won't run because previous stage failed
  
      - name: Stage 4 - Deploy to AWS
        debug:
          msg: "Deploying app to AWS EC2..."
        when: false  # Won’t run
  
      - name: Stage 5 - Deployment Complete
        debug:
          msg: "🎉 Deployment simulation finished!"
        when: false  # Won’t run