---
  - name: Dummy Spring Boot CI/CD Pipeline with Simulated Failure
    hosts: localhost
    gather_facts: no
    become: no
  
    vars:
      app_name: springboot-app
      jar_file: target/app.jar
  
    tasks:
      - name: Stage 1 - Clean Workspace
        debug:
          msg: "Cleaning workspace..."
  
      - name: Stage 2 - Maven Clean Install (FAIL SIMULATED)
        fail:
          msg: "Maven build failed due to missing dependencies."
  
      - name: Stage 3 - Run Unit Tests
        debug:
          msg: "Running JUnit test cases..."
        when: false
  
      - name: Stage 4 - Deploy to AWS
        debug:
          msg: "Deploying app to AWS EC2..."
        when: false
  
      - name: Stage 5 - Deployment Complete
        debug:
          msg: "🎉 Deployment simulation finished!"
        when: false